### ISSUE TITLE
Interesting stuff.. it's just..

### ISSUE THREAD

**Issue by shogunsea** [tifa2UP/Netly#1]
it took 1min to load first 888b file:
![image](https://cloud.githubusercontent.com/assets/2238944/21081549/0bee6dc0-bf8f-11e6-9c40-95a01f0c3cdd.png)

I wonder why it took so long at the server side.

**Comment by tifa2UP** [comment]
Hey @shogunsea, we did some investigation and the delay is due to DNS

**Comment by tifa2UP** [comment]
Hey @shogunsea, It had to do with the DNS routing since we're serving the website off firebase then masking the domain. You won't experience this latency if you visit the original website directly: https://testingproject-cd660.firebaseapp.com/

**Comment by shogunsea** [comment]
@tifa2UP that makes sense, thanks for the clarification 👍
